### ISSUE TITLE
spanish translation

### ISSUE THREAD

**Issue by javierdlr** [mplpl/unrar_amiga#25]
[unrar_spanish.zip](https://github.com/mplpl/unrar_amiga/files/4313992/unrar_spanish.zip)

Hi I have an updated  spanish ct file. Attached.

BYW don't know if this is the "how tro proceed", as I'm not used to use web github (well niether cli git), sorry.

**Comment by mplpl** [comment]
Thank you Javier. I'll commit it to the code base soon.

**Comment by mplpl** [comment]
ct and catalog files added in 5.90

**Comment by mplpl** [comment]
@javierdlr I'm going to release a new version of unrar and I need your help with Spanish translation. Please contact me at marcin.labenski@gmail.com.
